# EXTREMELY MINIMAL WORKING PIPELINE
# APDS7311 Assignment - Start Here and Build Up

version: 2.1

jobs:
  basic-validation:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: "Basic Health Check"
          command: |
            echo "✅ Repository checked out successfully"
            echo "✅ Node.js version: $(node --version)"
            echo "✅ NPM version: $(npm --version)"
            echo "✅ Checking project structure..."
            ls -la
            echo "✅ Server directory exists: $(test -d server && echo 'YES' || echo 'NO')"
            echo "✅ Client directory exists: $(test -d client && echo 'YES' || echo 'NO')"
            echo "✅ Pipeline completed successfully!"

workflows:
  extremely-minimal:
    jobs:
      - basic-validation
