version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.20.4
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: server
      - node/install-packages:
          pkg-manager: npm
          app-dir: client
      - run:
          name: Test Server Syntax
          command: |
            cd server
            node -c index.js
            echo "✅ Server syntax validation passed"
      - run:
          name: Run Basic Server Tests
          command: |
            cd server
            # Check if all required files exist
            echo "Checking server structure..."
            ls -la config/ models/ routes/ middleware/ utils/
            echo "✅ Server structure validation passed"
      - run:
          name: Build Client Application
          command: |
            cd client
            npm run build
            echo "✅ Client build completed successfully"
      - run:
          name: Security Audit
          command: |
            echo "Running security audits..."
            cd server
            npm audit --audit-level high || echo "Server audit completed with warnings"
            cd ../client
            npm audit --audit-level high || echo "Client audit completed with warnings"
      - run:
          name: Code Quality Check
          command: |
            echo "Running basic code quality checks..."
            cd server
            echo "Checking for .env files in repo..."
            if find . -name "*.env" -not -path "./node_modules/*" | head -5; then
              echo "⚠️  Warning: .env files detected in repository"
            else
              echo "✅ No .env files found in repository"
            fi
            echo "Checking file permissions..."
            ls -la index.js config/ models/ routes/
            echo "✅ Code quality check completed"

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
