version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/node:18.20.4'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            echo "Installing server dependencies..."
            cd server && npm install && cd ..
            echo "Installing client dependencies..."
            cd client && npm install && npm run build && cd ..
            echo "Dependency installation and client build complete."
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
