version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/node:18.20.4
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: server
      - node/install-packages:
          pkg-manager: npm
          app-dir: client
      - run:
          name: Test Server
          command: |
            cd server
            node -c index.js
      - run:
          name: Build Client
          command: |
            cd client
            npm run build

workflows:
  main:
    jobs:
      - build
